### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [wenqiglantz/spring-native-spring-boot-customer-service#1]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by wenqiglantz** [comment]
Thank you for your question!  I chose Spring Native because I wanted to demonstrate how Spring Native helps boost microservices built with Spring Boot framework.  Spring Boot is by far the most popular framework for microservices, market share far surpasses Quarkus or Micronaut.  With Spring Native, Spring Boot now has a more competitive advantage over other frameworks for microservice development.  Please check out my Medium story on Spring Native, you can find the details on the pros and cons of Spring Native there, https://betterprogramming.pub/how-to-integrate-spring-native-into-spring-boot-microservices-add2ece541b8?sk=6ba4674550db30783f7c5c68ba13c141.
